/** Unique Second Century ledger specs. Stages 61–160. */
import type { Verb } from "./recipe";
import type { LandOp } from "./sculpt";
import type { ThemeId } from "./types";

export type CenturySetpiece =
  | "colonnade"
  | "zipper"
  | "terrace"
  | "ice"
  | "ribs"
  | "torches"
  | "dual-loft"
  | "vent"
  | "switchback"
  | "court";

export type CenturySilhouette =
  | "hill-valley"
  | "valley-hill"
  | "twin-hills"
  | "ridge-pass"
  | "canal-bridge"
  | "court-pass"
  | "pit-chain"
  | "loft-street"
  | "saw-rail"
  | "shutter-gallery"
  | "echo-lofts"
  | "carriage-canyon"
  | "laser-nave"
  | "geyser-row"
  | "rotor-court"
  | "ice-shelf"
  | "rib-climb"
  | "mixed-sentence"
  | "pass-court-pass"
  | "well-loft-well";

export interface CenturySpec {
  n: number;
  name: string;
  objective: string;
  theme: ThemeId;
  featured: Verb;
  mix: Verb;
  silhouette: CenturySilhouette;
  setpiece: CenturySetpiece;
  w: number;
  land: LandOp[];
  teachX: number;
  mixX: number;
  extraX: number;
  restX: number;
  porchAX: number;
  porchBX: number;
  setX: number;
  pocketX: number;
  porchA: string;
  porchB: string;
  prize: "$" | "i";
}

export const CENTURY: CenturySpec[] = [
  {
    n: 61,
    name: 'Press Forge',
    objective: 'Teach the stamper. Mix the guillotine. Rest between packs. Reach the gate.',
    theme: 'fort',
    featured: 'z',
    mix: 'x',
    silhouette: 'hill-valley',
    setpiece: 'colonnade',
    w: 132,
    land: [{ t: "hill", at: 13, w: 11, h: 2 }, { t: "pass", at: 45, w: 18 }, { t: "pass", at: 72, w: 19 }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 59,
    porchAX: 31,
    porchBX: 87,
    setX: 67,
    pocketX: 109,
    porchA: '89A',
    porchB: '8A9',
    prize: 'i',
  },
  {
    n: 62,
    name: 'Censer Wharf',
    objective: 'Teach the swinging censer. Mix the bounce pit. Rest between packs. Reach the gate.',
    theme: 'canal',
    featured: 'l',
    mix: 'T',
    silhouette: 'valley-hill',
    setpiece: 'ice',
    w: 136,
    land: [{ t: "valley", at: 14, w: 12, d: 2 }, { t: "hill", at: 42, w: 13, h: 2 }, { t: "ridge", at: 72, w: 18 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 60,
    porchAX: 32,
    porchBX: 88,
    setX: 69,
    pocketX: 112,
    porchA: 'BCE',
    porchB: 'B9E',
    prize: 'i',
  },
  {
    n: 63,
    name: 'Guillotine Spring',
    objective: 'Teach the guillotine. Mix the swinging censer. Rest between packs. Reach the gate.',
    theme: 'coil',
    featured: 'x',
    mix: 'l',
    silhouette: 'twin-hills',
    setpiece: 'dual-loft',
    w: 104,
    land: [{ t: "hill", at: 15, w: 13, h: 2 }, { t: "hill", at: 45, w: 14, h: 1 }, { t: "valley", at: 72, w: 10, d: 2 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 58,
    porchAX: 33,
    porchBX: 89,
    setX: 64,
    pocketX: 79,
    porchA: 'Y75',
    porchB: 'C9Y',
    prize: 'i',
  },
  {
    n: 64,
    name: 'Drop-Cap Folio',
    objective: 'Teach the falling drop-cap. Mix the swinging censer. Rest between packs. Reach the gate.',
    theme: 'vault',
    featured: 'f',
    mix: 'l',
    silhouette: 'ridge-pass',
    setpiece: 'court',
    w: 108,
    land: [{ t: "ridge", at: 12, w: 18 }, { t: "pass", at: 42, w: 16 }, { t: "hill", at: 72, w: 11, h: 1 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 59,
    porchAX: 34,
    porchBX: 86,
    setX: 66,
    pocketX: 86,
    porchA: '8A9',
    porchB: 'B2C',
    prize: '$',
  },
  {
    n: 65,
    name: 'The Case',
    objective: 'Teach the rotor court. Mix the guillotine. Two packs, then the warden. Take the gate.',
    theme: 'abyss',
    featured: 'd',
    mix: 'x',
    silhouette: 'canal-bridge',
    setpiece: 'terrace',
    w: 112,
    land: [{ t: "hill", at: 13, w: 10, h: 2 }, { t: "valley", at: 45, w: 11, d: 2 }, { t: "bridge", at: 72, w: 10, ride: "{" }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 60,
    porchAX: 30,
    porchBX: 87,
    setX: 68,
    pocketX: 89,
    porchA: 'B2C',
    porchB: '!Y8',
    prize: 'i',
  },
  {
    n: 66,
    name: 'Basin Stair',
    objective: 'Teach the ink basin. Mix the ember grate. Rest between packs. Reach the gate.',
    theme: 'spire',
    featured: 'w',
    mix: 'j',
    silhouette: 'court-pass',
    setpiece: 'torches',
    w: 116,
    land: [{ t: "valley", at: 14, w: 11, d: 2 }, { t: "valley", at: 42, w: 12, d: 2 }, { t: "pass", at: 72, w: 19 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 58,
    porchAX: 31,
    porchBX: 88,
    setX: 70,
    pocketX: 92,
    porchA: 'E7Y',
    porchB: 'E87',
    prize: 'i',
  },
  {
    n: 67,
    name: 'Grate Orrery',
    objective: 'Teach the ember grate. Mix the floor geyser. Rest between packs. Reach the gate.',
    theme: 'orbit',
    featured: 'j',
    mix: 'g',
    silhouette: 'pit-chain',
    setpiece: 'switchback',
    w: 120,
    land: [{ t: "valley", at: 15, w: 12, d: 2 }, { t: "valley", at: 45, w: 13, d: 2 }, { t: "ridge", at: 72, w: 18 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 59,
    porchAX: 32,
    porchBX: 89,
    setX: 65,
    pocketX: 95,
    porchA: '98B',
    porchB: 'E7Y',
    prize: 'i',
  },
  {
    n: 68,
    name: 'Carriage Crevasse',
    objective: 'Teach the riding carriage. Mix the echo plate. Rest between packs. Reach the gate.',
    theme: 'glacier',
    featured: '{',
    mix: '[',
    silhouette: 'loft-street',
    setpiece: 'zipper',
    w: 124,
    land: [{ t: "bridge", at: 12, w: 11, ride: "{" }, { t: "hill", at: 42, w: 14, h: 2 }, { t: "hill", at: 72, w: 10, h: 1 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 60,
    porchAX: 33,
    porchBX: 86,
    setX: 67,
    pocketX: 102,
    porchA: 'CA5',
    porchB: 'C75',
    prize: '$',
  },
  {
    n: 69,
    name: 'Echo Sentence',
    objective: 'Teach the echo plate. Mix the shutter window. Rest between packs. Reach the gate.',
    theme: 'remainder',
    featured: '[',
    mix: '}',
    silhouette: 'saw-rail',
    setpiece: 'ribs',
    w: 128,
    land: [{ t: "hill", at: 13, w: 14, h: 2 }, { t: "pass", at: 45, w: 16 }, { t: "pass", at: 72, w: 17 }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 58,
    porchAX: 34,
    porchBX: 87,
    setX: 69,
    pocketX: 105,
    porchA: '7YE',
    porchB: 'A9B',
    prize: 'i',
  },
  {
    n: 70,
    name: 'The Imposing Stone',
    objective: 'Teach the shutter window. Mix the rotor court. Two packs, then the warden. Take the gate.',
    theme: 'street',
    featured: '}',
    mix: 'd',
    silhouette: 'shutter-gallery',
    setpiece: 'vent',
    w: 132,
    land: [{ t: "pass", at: 14, w: 16 }, { t: "hill", at: 42, w: 11, h: 2 }, { t: "ridge", at: 72, w: 16 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 59,
    porchAX: 30,
    porchBX: 88,
    setX: 64,
    pocketX: 108,
    porchA: 'A8C',
    porchB: '!98',
    prize: 'i',
  },
  {
    n: 71,
    name: 'Saw Forge',
    objective: 'Teach the hanging saw. Mix the loft laser. Rest between packs. Reach the gate.',
    theme: 'fort',
    featured: 'S',
    mix: '|',
    silhouette: 'echo-lofts',
    setpiece: 'colonnade',
    w: 136,
    land: [{ t: "ridge", at: 15, w: 15 }, { t: "pass", at: 45, w: 18 }, { t: "valley", at: 72, w: 13, d: 2 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 60,
    porchAX: 31,
    porchBX: 89,
    setX: 66,
    pocketX: 111,
    porchA: 'B9E',
    porchB: '9BE',
    prize: 'i',
  },
  {
    n: 72,
    name: 'Lift Wharf',
    objective: 'Teach the lift shaft. Mix the blink pad. Rest between packs. Reach the gate.',
    theme: 'canal',
    featured: '`',
    mix: ')',
    silhouette: 'carriage-canyon',
    setpiece: 'ice',
    w: 104,
    land: [{ t: "valley", at: 12, w: 12, d: 2 }, { t: "valley", at: 42, w: 13, d: 2 }, { t: "hill", at: 72, w: 14, h: 1 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 58,
    porchAX: 32,
    porchBX: 86,
    setX: 68,
    pocketX: 82,
    porchA: 'Y8A',
    porchB: '89A',
    prize: '$',
  },
  {
    n: 73,
    name: 'Geyser Spring',
    objective: 'Teach the floor geyser. Mix the lift shaft. Rest between packs. Reach the gate.',
    theme: 'coil',
    featured: 'g',
    mix: '`',
    silhouette: 'laser-nave',
    setpiece: 'dual-loft',
    w: 108,
    land: [{ t: "valley", at: 13, w: 13, d: 2 }, { t: "valley", at: 45, w: 14, d: 2 }, { t: "pass", at: 72, w: 16 }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 59,
    porchAX: 33,
    porchBX: 87,
    setX: 70,
    pocketX: 85,
    porchA: 'C75',
    porchB: 'CA5',
    prize: 'i',
  },
  {
    n: 74,
    name: 'Blink Folio',
    objective: 'Teach the blink pad. Mix the hanging saw. Rest between packs. Reach the gate.',
    theme: 'vault',
    featured: ')',
    mix: 'S',
    silhouette: 'geyser-row',
    setpiece: 'court',
    w: 112,
    land: [{ t: "valley", at: 14, w: 14, d: 2 }, { t: "ridge", at: 42, w: 14 }, { t: "ridge", at: 72, w: 15 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 60,
    porchAX: 34,
    porchBX: 88,
    setX: 65,
    pocketX: 88,
    porchA: '9BE',
    porchB: 'A7C',
    prize: 'i',
  },
  {
    n: 75,
    name: 'Flood Warden',
    objective: 'Teach the loft laser. Mix the belt slope. Two packs, then the warden. Take the gate.',
    theme: 'abyss',
    featured: '|',
    mix: '/',
    silhouette: 'rotor-court',
    setpiece: 'terrace',
    w: 116,
    land: [{ t: "pass", at: 15, w: 16 }, { t: "hill", at: 45, w: 11, h: 1 }, { t: "valley", at: 72, w: 12, d: 2 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 58,
    porchAX: 30,
    porchBX: 89,
    setX: 67,
    pocketX: 91,
    porchA: 'A7C',
    porchB: '!BC',
    prize: 'i',
  },
  {
    n: 76,
    name: 'Belt Stair',
    objective: 'Teach the belt slope. Mix the crumble run. Rest between packs. Reach the gate.',
    theme: 'spire',
    featured: '/',
    mix: '-',
    silhouette: 'ice-shelf',
    setpiece: 'torches',
    w: 120,
    land: [{ t: "hill", at: 12, w: 11, h: 1 }, { t: "hill", at: 42, w: 12, h: 2 }, { t: "valley", at: 72, w: 13, d: 2 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 59,
    porchAX: 31,
    porchBX: 86,
    setX: 69,
    pocketX: 98,
    porchA: '8YE',
    porchB: '7YE',
    prize: '$',
  },
  {
    n: 77,
    name: 'Bounce Orrery',
    objective: 'Teach the bounce pit. Mix the belt slope. Rest between packs. Reach the gate.',
    theme: 'orbit',
    featured: 'T',
    mix: '/',
    silhouette: 'rib-climb',
    setpiece: 'switchback',
    w: 124,
    land: [{ t: "valley", at: 13, w: 12, d: 2 }, { t: "hill", at: 45, w: 13, h: 1 }, { t: "pass", at: 72, w: 20 }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 60,
    porchAX: 32,
    porchBX: 87,
    setX: 64,
    pocketX: 101,
    porchA: 'B5A',
    porchB: '8YE',
    prize: 'i',
  },
  {
    n: 78,
    name: 'Crumble Crevasse',
    objective: 'Teach the crumble run. Mix the bounce pit. Rest between packs. Reach the gate.',
    theme: 'glacier',
    featured: '-',
    mix: 'T',
    silhouette: 'mixed-sentence',
    setpiece: 'zipper',
    w: 128,
    land: [{ t: "hill", at: 14, w: 13, h: 1 }, { t: "valley", at: 42, w: 14, d: 2 }, { t: "ridge", at: 72, w: 14 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 58,
    porchAX: 33,
    porchBX: 88,
    setX: 66,
    pocketX: 104,
    porchA: 'C9Y',
    porchB: 'Y75',
    prize: 'i',
  },
  {
    n: 79,
    name: 'Loft Sentence',
    objective: 'Teach the loft street. Mix the crumble run. Rest between packs. Reach the gate.',
    theme: 'remainder',
    featured: '=',
    mix: '-',
    silhouette: 'pass-court-pass',
    setpiece: 'ribs',
    w: 132,
    land: [{ t: "hill", at: 15, w: 14, h: 2 }, { t: "hill", at: 45, w: 10, h: 1 }, { t: "valley", at: 72, w: 11, d: 2 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 59,
    porchAX: 34,
    porchBX: 89,
    setX: 68,
    pocketX: 107,
    porchA: 'E87',
    porchB: 'A8C',
    prize: 'i',
  },
  {
    n: 80,
    name: 'The Wet Account',
    objective: 'Teach the swinging censer. Mix the bounce pit. Two packs, then the warden. Take the gate.',
    theme: 'street',
    featured: 'l',
    mix: 'T',
    silhouette: 'well-loft-well',
    setpiece: 'vent',
    w: 136,
    land: [{ t: "hill", at: 12, w: 10, h: 1 }, { t: "valley", at: 42, w: 11, d: 2 }, { t: "valley", at: 72, w: 12, d: 2 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 60,
    porchAX: 30,
    porchBX: 86,
    setX: 70,
    pocketX: 114,
    porchA: 'A9B',
    porchB: '!B5',
    prize: '$',
  },
  {
    n: 81,
    name: 'Press Forge 81',
    objective: 'Teach the stamper. Mix the swinging censer. Rest between packs. Reach the gate.',
    theme: 'fort',
    featured: 'z',
    mix: 'l',
    silhouette: 'hill-valley',
    setpiece: 'colonnade',
    w: 104,
    land: [{ t: "hill", at: 13, w: 11, h: 2 }, { t: "hill", at: 45, w: 12, h: 1 }, { t: "pass", at: 72, w: 19 }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 58,
    porchAX: 31,
    porchBX: 87,
    setX: 65,
    pocketX: 81,
    porchA: '89A',
    porchB: '8A9',
    prize: 'i',
  },
  {
    n: 82,
    name: 'Censer Wharf 82',
    objective: 'Teach the swinging censer. Mix the sluice (mix only). Rest between packs. Reach the gate.',
    theme: 'canal',
    featured: 'l',
    mix: '~',
    silhouette: 'valley-hill',
    setpiece: 'ice',
    w: 108,
    land: [{ t: "valley", at: 14, w: 12, d: 2 }, { t: "hill", at: 42, w: 13, h: 2 }, { t: "ridge", at: 72, w: 18 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 59,
    porchAX: 32,
    porchBX: 88,
    setX: 67,
    pocketX: 84,
    porchA: 'BCE',
    porchB: 'B9E',
    prize: 'i',
  },
  {
    n: 83,
    name: 'Guillotine Spring 83',
    objective: 'Teach the guillotine. Mix the loft laser. Rest between packs. Reach the gate.',
    theme: 'coil',
    featured: 'x',
    mix: '|',
    silhouette: 'twin-hills',
    setpiece: 'dual-loft',
    w: 112,
    land: [{ t: "hill", at: 15, w: 13, h: 2 }, { t: "hill", at: 45, w: 14, h: 1 }, { t: "valley", at: 72, w: 10, d: 2 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 60,
    porchAX: 33,
    porchBX: 89,
    setX: 69,
    pocketX: 87,
    porchA: 'Y75',
    porchB: 'C9Y',
    prize: 'i',
  },
  {
    n: 84,
    name: 'Drop-Cap Folio 84',
    objective: 'Teach the falling drop-cap. Mix the stamper. Rest between packs. Reach the gate.',
    theme: 'vault',
    featured: 'f',
    mix: 'z',
    silhouette: 'ridge-pass',
    setpiece: 'court',
    w: 116,
    land: [{ t: "ridge", at: 12, w: 18 }, { t: "pass", at: 42, w: 16 }, { t: "hill", at: 72, w: 11, h: 1 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 58,
    porchAX: 34,
    porchBX: 86,
    setX: 64,
    pocketX: 94,
    porchA: '8A9',
    porchB: 'B2C',
    prize: '$',
  },
  {
    n: 85,
    name: 'Coil Warden',
    objective: 'Teach the rotor court. Mix the echo plate. Two packs, then the warden. Take the gate.',
    theme: 'abyss',
    featured: 'd',
    mix: '[',
    silhouette: 'canal-bridge',
    setpiece: 'terrace',
    w: 120,
    land: [{ t: "hill", at: 13, w: 10, h: 2 }, { t: "valley", at: 45, w: 11, d: 2 }, { t: "bridge", at: 72, w: 10, ride: "{" }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 59,
    porchAX: 30,
    porchBX: 87,
    setX: 66,
    pocketX: 97,
    porchA: 'B2C',
    porchB: '!Y8',
    prize: 'i',
  },
  {
    n: 86,
    name: 'Basin Stair 86',
    objective: 'Teach the ink basin. Mix the bounce pit. Rest between packs. Reach the gate.',
    theme: 'spire',
    featured: 'w',
    mix: 'T',
    silhouette: 'court-pass',
    setpiece: 'torches',
    w: 124,
    land: [{ t: "valley", at: 14, w: 11, d: 2 }, { t: "valley", at: 42, w: 12, d: 2 }, { t: "pass", at: 72, w: 19 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 60,
    porchAX: 31,
    porchBX: 88,
    setX: 68,
    pocketX: 100,
    porchA: 'E7Y',
    porchB: 'E87',
    prize: 'i',
  },
  {
    n: 87,
    name: 'Grate Orrery 87',
    objective: 'Teach the ember grate. Mix the ink basin. Rest between packs. Reach the gate.',
    theme: 'orbit',
    featured: 'j',
    mix: 'w',
    silhouette: 'pit-chain',
    setpiece: 'switchback',
    w: 128,
    land: [{ t: "valley", at: 15, w: 12, d: 2 }, { t: "valley", at: 45, w: 13, d: 2 }, { t: "ridge", at: 72, w: 18 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 58,
    porchAX: 32,
    porchBX: 89,
    setX: 70,
    pocketX: 103,
    porchA: '98B',
    porchB: 'E7Y',
    prize: 'i',
  },
  {
    n: 88,
    name: 'Carriage Crevasse 88',
    objective: 'Teach the riding carriage. Mix the blink pad. Rest between packs. Reach the gate.',
    theme: 'glacier',
    featured: '{',
    mix: ')',
    silhouette: 'loft-street',
    setpiece: 'zipper',
    w: 132,
    land: [{ t: "bridge", at: 12, w: 11, ride: "{" }, { t: "valley", at: 42, w: 14, d: 2 }, { t: "hill", at: 72, w: 10, h: 1 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 59,
    porchAX: 33,
    porchBX: 86,
    setX: 65,
    pocketX: 110,
    porchA: 'CA5',
    porchB: 'C75',
    prize: '$',
  },
  {
    n: 89,
    name: 'Echo Sentence 89',
    objective: 'Teach the echo plate. Mix the loft street. Rest between packs. Reach the gate.',
    theme: 'remainder',
    featured: '[',
    mix: '=',
    silhouette: 'saw-rail',
    setpiece: 'ribs',
    w: 136,
    land: [{ t: "hill", at: 13, w: 14, h: 2 }, { t: "hill", at: 45, w: 10, h: 1 }, { t: "pass", at: 72, w: 17 }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 60,
    porchAX: 34,
    porchBX: 87,
    setX: 67,
    pocketX: 113,
    porchA: '7YE',
    porchB: 'A9B',
    prize: 'i',
  },
  {
    n: 90,
    name: 'The Wound Spring',
    objective: 'Teach the shutter window. Mix the guillotine. Two packs, then the warden. Take the gate.',
    theme: 'street',
    featured: '}',
    mix: 'x',
    silhouette: 'shutter-gallery',
    setpiece: 'vent',
    w: 104,
    land: [{ t: "pass", at: 14, w: 16 }, { t: "pass", at: 42, w: 17 }, { t: "ridge", at: 72, w: 16 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 58,
    porchAX: 30,
    porchBX: 88,
    setX: 69,
    pocketX: 80,
    porchA: 'A8C',
    porchB: '!98',
    prize: 'i',
  },
  {
    n: 91,
    name: 'Saw Forge 91',
    objective: 'Teach the hanging saw. Mix the blink pad. Rest between packs. Reach the gate.',
    theme: 'fort',
    featured: 'S',
    mix: ')',
    silhouette: 'echo-lofts',
    setpiece: 'colonnade',
    w: 108,
    land: [{ t: "ridge", at: 15, w: 15 }, { t: "valley", at: 45, w: 12, d: 2 }, { t: "valley", at: 72, w: 13, d: 2 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 59,
    porchAX: 31,
    porchBX: 89,
    setX: 64,
    pocketX: 83,
    porchA: 'B9E',
    porchB: '9BE',
    prize: 'i',
  },
  {
    n: 92,
    name: 'Lift Wharf 92',
    objective: 'Teach the lift shaft. Mix the bounce pit. Rest between packs. Reach the gate.',
    theme: 'canal',
    featured: '`',
    mix: 'T',
    silhouette: 'carriage-canyon',
    setpiece: 'ice',
    w: 112,
    land: [{ t: "valley", at: 12, w: 12, d: 2 }, { t: "valley", at: 42, w: 13, d: 2 }, { t: "hill", at: 72, w: 14, h: 1 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 60,
    porchAX: 32,
    porchBX: 86,
    setX: 66,
    pocketX: 90,
    porchA: 'Y8A',
    porchB: '89A',
    prize: '$',
  },
  {
    n: 93,
    name: 'Geyser Spring 93',
    objective: 'Teach the floor geyser. Mix the ink basin. Rest between packs. Reach the gate.',
    theme: 'coil',
    featured: 'g',
    mix: 'w',
    silhouette: 'laser-nave',
    setpiece: 'dual-loft',
    w: 116,
    land: [{ t: "valley", at: 13, w: 13, d: 2 }, { t: "valley", at: 45, w: 14, d: 2 }, { t: "pass", at: 72, w: 16 }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 58,
    porchAX: 33,
    porchBX: 87,
    setX: 68,
    pocketX: 93,
    porchA: 'C75',
    porchB: 'CA5',
    prize: 'i',
  },
  {
    n: 94,
    name: 'Blink Folio 94',
    objective: 'Teach the blink pad. Mix the bounce pit. Rest between packs. Reach the gate.',
    theme: 'vault',
    featured: ')',
    mix: 'T',
    silhouette: 'geyser-row',
    setpiece: 'court',
    w: 120,
    land: [{ t: "valley", at: 14, w: 14, d: 2 }, { t: "valley", at: 42, w: 10, d: 2 }, { t: "ridge", at: 72, w: 15 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 59,
    porchAX: 34,
    porchBX: 88,
    setX: 70,
    pocketX: 96,
    porchA: '9BE',
    porchB: 'A7C',
    prize: 'i',
  },
  {
    n: 95,
    name: 'Ice Warden',
    objective: 'Teach the loft laser. Mix the guillotine. Two packs, then the warden. Take the gate.',
    theme: 'abyss',
    featured: '|',
    mix: 'x',
    silhouette: 'rotor-court',
    setpiece: 'terrace',
    w: 124,
    land: [{ t: "pass", at: 15, w: 16 }, { t: "pass", at: 45, w: 17 }, { t: "valley", at: 72, w: 12, d: 2 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 60,
    porchAX: 30,
    porchBX: 89,
    setX: 65,
    pocketX: 99,
    porchA: 'A7C',
    porchB: '!BC',
    prize: 'i',
  },
  {
    n: 96,
    name: 'Belt Stair 96',
    objective: 'Teach the belt slope. Mix the bounce pit. Rest between packs. Reach the gate.',
    theme: 'spire',
    featured: '/',
    mix: 'T',
    silhouette: 'ice-shelf',
    setpiece: 'torches',
    w: 128,
    land: [{ t: "hill", at: 12, w: 11, h: 1 }, { t: "valley", at: 42, w: 12, d: 2 }, { t: "valley", at: 72, w: 13, d: 2 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 58,
    porchAX: 31,
    porchBX: 86,
    setX: 67,
    pocketX: 106,
    porchA: '8YE',
    porchB: '7YE',
    prize: '$',
  },
  {
    n: 97,
    name: 'Bounce Orrery 97',
    objective: 'Teach the bounce pit. Mix the loft street. Rest between packs. Reach the gate.',
    theme: 'orbit',
    featured: 'T',
    mix: '=',
    silhouette: 'rib-climb',
    setpiece: 'switchback',
    w: 132,
    land: [{ t: "valley", at: 13, w: 12, d: 2 }, { t: "hill", at: 45, w: 13, h: 1 }, { t: "pass", at: 72, w: 20 }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 59,
    porchAX: 32,
    porchBX: 87,
    setX: 69,
    pocketX: 109,
    porchA: 'B5A',
    porchB: '8YE',
    prize: 'i',
  },
  {
    n: 98,
    name: 'Crumble Crevasse 98',
    objective: 'Teach the crumble run. Mix the lift shaft. Rest between packs. Reach the gate.',
    theme: 'glacier',
    featured: '-',
    mix: '`',
    silhouette: 'mixed-sentence',
    setpiece: 'zipper',
    w: 136,
    land: [{ t: "hill", at: 14, w: 13, h: 1 }, { t: "valley", at: 42, w: 14, d: 2 }, { t: "ridge", at: 72, w: 14 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 60,
    porchAX: 33,
    porchBX: 88,
    setX: 64,
    pocketX: 112,
    porchA: 'C9Y',
    porchB: 'Y75',
    prize: 'i',
  },
  {
    n: 99,
    name: 'Loft Sentence 99',
    objective: 'Teach the loft street. Mix the loft laser. Rest between packs. Reach the gate.',
    theme: 'remainder',
    featured: '=',
    mix: '|',
    silhouette: 'pass-court-pass',
    setpiece: 'ribs',
    w: 104,
    land: [{ t: "hill", at: 15, w: 14, h: 2 }, { t: "pass", at: 45, w: 16 }, { t: "valley", at: 72, w: 11, d: 2 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 58,
    porchAX: 34,
    porchBX: 89,
    setX: 66,
    pocketX: 79,
    porchA: 'E87',
    porchB: 'A8C',
    prize: 'i',
  },
  {
    n: 100,
    name: 'The Packed Period',
    objective: 'Teach the swinging censer. Mix the guillotine. Two packs, then the warden. Take the gate.',
    theme: 'street',
    featured: 'l',
    mix: 'x',
    silhouette: 'well-loft-well',
    setpiece: 'vent',
    w: 108,
    land: [{ t: "hill", at: 12, w: 10, h: 1 }, { t: "pass", at: 42, w: 17 }, { t: "valley", at: 72, w: 12, d: 2 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 59,
    porchAX: 30,
    porchBX: 86,
    setX: 68,
    pocketX: 86,
    porchA: 'A9B',
    porchB: '!B5',
    prize: '$',
  },
  {
    n: 101,
    name: 'Press Forge 101',
    objective: 'Teach the stamper. Mix the falling drop-cap. Rest between packs. Reach the gate.',
    theme: 'fort',
    featured: 'z',
    mix: 'f',
    silhouette: 'hill-valley',
    setpiece: 'colonnade',
    w: 112,
    land: [{ t: "hill", at: 13, w: 11, h: 2 }, { t: "hill", at: 45, w: 12, h: 1 }, { t: "pass", at: 72, w: 19 }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 60,
    porchAX: 31,
    porchBX: 87,
    setX: 70,
    pocketX: 89,
    porchA: '89A',
    porchB: '8A9',
    prize: 'i',
  },
  {
    n: 102,
    name: 'Censer Wharf 102',
    objective: 'Teach the swinging censer. Mix the stamper. Rest between packs. Reach the gate.',
    theme: 'canal',
    featured: 'l',
    mix: 'z',
    silhouette: 'valley-hill',
    setpiece: 'ice',
    w: 116,
    land: [{ t: "valley", at: 14, w: 12, d: 2 }, { t: "hill", at: 42, w: 13, h: 2 }, { t: "ridge", at: 72, w: 18 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 58,
    porchAX: 32,
    porchBX: 88,
    setX: 65,
    pocketX: 92,
    porchA: 'BCE',
    porchB: 'B9E',
    prize: 'i',
  },
  {
    n: 103,
    name: 'Guillotine Spring 103',
    objective: 'Teach the guillotine. Mix the shutter window. Rest between packs. Reach the gate.',
    theme: 'coil',
    featured: 'x',
    mix: '}',
    silhouette: 'twin-hills',
    setpiece: 'dual-loft',
    w: 120,
    land: [{ t: "hill", at: 15, w: 13, h: 2 }, { t: "hill", at: 45, w: 14, h: 1 }, { t: "valley", at: 72, w: 10, d: 2 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 59,
    porchAX: 33,
    porchBX: 89,
    setX: 67,
    pocketX: 95,
    porchA: 'Y75',
    porchB: 'C9Y',
    prize: 'i',
  },
  {
    n: 104,
    name: 'Drop-Cap Folio 104',
    objective: 'Teach the falling drop-cap. Mix the lift shaft. Rest between packs. Reach the gate.',
    theme: 'vault',
    featured: 'f',
    mix: '`',
    silhouette: 'ridge-pass',
    setpiece: 'court',
    w: 124,
    land: [{ t: "ridge", at: 12, w: 18 }, { t: "pass", at: 42, w: 16 }, { t: "hill", at: 72, w: 11, h: 1 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 60,
    porchAX: 34,
    porchBX: 86,
    setX: 69,
    pocketX: 102,
    porchA: '8A9',
    porchB: 'B2C',
    prize: '$',
  },
  {
    n: 105,
    name: 'Orbit Warden',
    objective: 'Teach the rotor court. Mix the shutter window. Two packs, then the warden. Take the gate.',
    theme: 'abyss',
    featured: 'd',
    mix: '}',
    silhouette: 'canal-bridge',
    setpiece: 'terrace',
    w: 128,
    land: [{ t: "hill", at: 13, w: 10, h: 2 }, { t: "valley", at: 45, w: 11, d: 2 }, { t: "bridge", at: 72, w: 10, ride: "{" }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 58,
    porchAX: 30,
    porchBX: 87,
    setX: 64,
    pocketX: 105,
    porchA: 'B2C',
    porchB: '!Y8',
    prize: 'i',
  },
  {
    n: 106,
    name: 'Basin Stair 106',
    objective: 'Teach the ink basin. Mix the floor geyser. Rest between packs. Reach the gate.',
    theme: 'spire',
    featured: 'w',
    mix: 'g',
    silhouette: 'court-pass',
    setpiece: 'torches',
    w: 132,
    land: [{ t: "valley", at: 14, w: 11, d: 2 }, { t: "valley", at: 42, w: 12, d: 2 }, { t: "pass", at: 72, w: 19 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 59,
    porchAX: 31,
    porchBX: 88,
    setX: 66,
    pocketX: 108,
    porchA: 'E7Y',
    porchB: 'E87',
    prize: 'i',
  },
  {
    n: 107,
    name: 'Grate Orrery 107',
    objective: 'Teach the ember grate. Mix the crumble run. Rest between packs. Reach the gate.',
    theme: 'orbit',
    featured: 'j',
    mix: '-',
    silhouette: 'pit-chain',
    setpiece: 'switchback',
    w: 136,
    land: [{ t: "valley", at: 15, w: 12, d: 2 }, { t: "hill", at: 45, w: 13, h: 1 }, { t: "ridge", at: 72, w: 18 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 60,
    porchAX: 32,
    porchBX: 89,
    setX: 68,
    pocketX: 111,
    porchA: '98B',
    porchB: 'E7Y',
    prize: 'i',
  },
  {
    n: 108,
    name: 'Carriage Crevasse 108',
    objective: 'Teach the riding carriage. Mix the lift shaft. Rest between packs. Reach the gate.',
    theme: 'glacier',
    featured: '{',
    mix: '`',
    silhouette: 'loft-street',
    setpiece: 'zipper',
    w: 104,
    land: [{ t: "bridge", at: 12, w: 11, ride: "{" }, { t: "valley", at: 42, w: 14, d: 2 }, { t: "hill", at: 72, w: 10, h: 1 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 58,
    porchAX: 33,
    porchBX: 86,
    setX: 70,
    pocketX: 82,
    porchA: 'CA5',
    porchB: 'C75',
    prize: '$',
  },
  {
    n: 109,
    name: 'Echo Sentence 109',
    objective: 'Teach the echo plate. Mix the rotor court. Rest between packs. Reach the gate.',
    theme: 'remainder',
    featured: '[',
    mix: 'd',
    silhouette: 'saw-rail',
    setpiece: 'ribs',
    w: 108,
    land: [{ t: "hill", at: 13, w: 14, h: 2 }, { t: "hill", at: 45, w: 10, h: 1 }, { t: "pass", at: 72, w: 17 }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 59,
    porchAX: 34,
    porchBX: 87,
    setX: 65,
    pocketX: 85,
    porchA: '7YE',
    porchB: 'A9B',
    prize: 'i',
  },
  {
    n: 110,
    name: 'The Teal Circumflex',
    objective: 'Teach the shutter window. Mix the echo plate. Two packs, then the warden. Take the gate.',
    theme: 'street',
    featured: '}',
    mix: '[',
    silhouette: 'shutter-gallery',
    setpiece: 'vent',
    w: 112,
    land: [{ t: "pass", at: 14, w: 16 }, { t: "hill", at: 42, w: 11, h: 2 }, { t: "ridge", at: 72, w: 16 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 60,
    porchAX: 30,
    porchBX: 88,
    setX: 67,
    pocketX: 88,
    porchA: 'A8C',
    porchB: '!98',
    prize: 'i',
  },
  {
    n: 111,
    name: 'Saw Forge 111',
    objective: 'Teach the hanging saw. Mix the lift shaft. Rest between packs. Reach the gate.',
    theme: 'fort',
    featured: 'S',
    mix: '`',
    silhouette: 'echo-lofts',
    setpiece: 'colonnade',
    w: 116,
    land: [{ t: "ridge", at: 15, w: 15 }, { t: "valley", at: 45, w: 12, d: 2 }, { t: "valley", at: 72, w: 13, d: 2 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 58,
    porchAX: 31,
    porchBX: 89,
    setX: 69,
    pocketX: 91,
    porchA: 'B9E',
    porchB: '9BE',
    prize: 'i',
  },
  {
    n: 112,
    name: 'Lift Wharf 112',
    objective: 'Teach the lift shaft. Mix the sluice (mix only). Rest between packs. Reach the gate.',
    theme: 'canal',
    featured: '`',
    mix: '~',
    silhouette: 'carriage-canyon',
    setpiece: 'ice',
    w: 120,
    land: [{ t: "valley", at: 12, w: 12, d: 2 }, { t: "valley", at: 42, w: 13, d: 2 }, { t: "hill", at: 72, w: 14, h: 1 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 59,
    porchAX: 32,
    porchBX: 86,
    setX: 64,
    pocketX: 98,
    porchA: 'Y8A',
    porchB: '89A',
    prize: '$',
  },
  {
    n: 113,
    name: 'Geyser Spring 113',
    objective: 'Teach the floor geyser. Mix the ember grate. Rest between packs. Reach the gate.',
    theme: 'coil',
    featured: 'g',
    mix: 'j',
    silhouette: 'laser-nave',
    setpiece: 'dual-loft',
    w: 124,
    land: [{ t: "valley", at: 13, w: 13, d: 2 }, { t: "valley", at: 45, w: 14, d: 2 }, { t: "pass", at: 72, w: 16 }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 60,
    porchAX: 33,
    porchBX: 87,
    setX: 66,
    pocketX: 101,
    porchA: 'C75',
    porchB: 'CA5',
    prize: 'i',
  },
  {
    n: 114,
    name: 'Blink Folio 114',
    objective: 'Teach the blink pad. Mix the lift shaft. Rest between packs. Reach the gate.',
    theme: 'vault',
    featured: ')',
    mix: '`',
    silhouette: 'geyser-row',
    setpiece: 'court',
    w: 128,
    land: [{ t: "valley", at: 14, w: 14, d: 2 }, { t: "valley", at: 42, w: 10, d: 2 }, { t: "ridge", at: 72, w: 15 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 58,
    porchAX: 34,
    porchBX: 88,
    setX: 68,
    pocketX: 104,
    porchA: '9BE',
    porchB: 'A7C',
    prize: 'i',
  },
  {
    n: 115,
    name: 'Script Warden',
    objective: 'Teach the loft laser. Mix the loft street. Two packs, then the warden. Take the gate.',
    theme: 'abyss',
    featured: '|',
    mix: '=',
    silhouette: 'rotor-court',
    setpiece: 'terrace',
    w: 132,
    land: [{ t: "pass", at: 15, w: 16 }, { t: "hill", at: 45, w: 11, h: 1 }, { t: "valley", at: 72, w: 12, d: 2 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 59,
    porchAX: 30,
    porchBX: 89,
    setX: 70,
    pocketX: 107,
    porchA: 'A7C',
    porchB: '!BC',
    prize: 'i',
  },
  {
    n: 116,
    name: 'Belt Stair 116',
    objective: 'Teach the belt slope. Mix the loft laser. Rest between packs. Reach the gate.',
    theme: 'spire',
    featured: '/',
    mix: '|',
    silhouette: 'ice-shelf',
    setpiece: 'torches',
    w: 136,
    land: [{ t: "hill", at: 12, w: 11, h: 1 }, { t: "pass", at: 42, w: 18 }, { t: "valley", at: 72, w: 13, d: 2 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 60,
    porchAX: 31,
    porchBX: 86,
    setX: 65,
    pocketX: 114,
    porchA: '8YE',
    porchB: '7YE',
    prize: '$',
  },
  {
    n: 117,
    name: 'Bounce Orrery 117',
    objective: 'Teach the bounce pit. Mix the crumble run. Rest between packs. Reach the gate.',
    theme: 'orbit',
    featured: 'T',
    mix: '-',
    silhouette: 'rib-climb',
    setpiece: 'switchback',
    w: 104,
    land: [{ t: "valley", at: 13, w: 12, d: 2 }, { t: "hill", at: 45, w: 13, h: 1 }, { t: "pass", at: 72, w: 20 }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 58,
    porchAX: 32,
    porchBX: 87,
    setX: 67,
    pocketX: 81,
    porchA: 'B5A',
    porchB: '8YE',
    prize: 'i',
  },
  {
    n: 118,
    name: 'Crumble Crevasse 118',
    objective: 'Teach the crumble run. Mix the loft street. Rest between packs. Reach the gate.',
    theme: 'glacier',
    featured: '-',
    mix: '=',
    silhouette: 'mixed-sentence',
    setpiece: 'zipper',
    w: 108,
    land: [{ t: "hill", at: 14, w: 13, h: 1 }, { t: "hill", at: 42, w: 14, h: 2 }, { t: "ridge", at: 72, w: 14 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 59,
    porchAX: 33,
    porchBX: 88,
    setX: 69,
    pocketX: 84,
    porchA: 'C9Y',
    porchB: 'Y75',
    prize: 'i',
  },
  {
    n: 119,
    name: 'Loft Sentence 119',
    objective: 'Teach the loft street. Mix the bounce pit. Rest between packs. Reach the gate.',
    theme: 'remainder',
    featured: '=',
    mix: 'T',
    silhouette: 'pass-court-pass',
    setpiece: 'ribs',
    w: 112,
    land: [{ t: "hill", at: 15, w: 14, h: 2 }, { t: "valley", at: 45, w: 10, d: 2 }, { t: "valley", at: 72, w: 11, d: 2 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 60,
    porchAX: 34,
    porchBX: 89,
    setX: 64,
    pocketX: 87,
    porchA: 'E87',
    porchB: 'A8C',
    prize: 'i',
  },
  {
    n: 120,
    name: 'The Unfiled Mark',
    objective: 'Teach the swinging censer. Mix the stamper. Two packs, then the warden. Take the gate.',
    theme: 'street',
    featured: 'l',
    mix: 'z',
    silhouette: 'well-loft-well',
    setpiece: 'vent',
    w: 116,
    land: [{ t: "hill", at: 12, w: 10, h: 1 }, { t: "hill", at: 42, w: 11, h: 2 }, { t: "valley", at: 72, w: 12, d: 2 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 58,
    porchAX: 30,
    porchBX: 86,
    setX: 66,
    pocketX: 94,
    porchA: 'A9B',
    porchB: '!B5',
    prize: '$',
  },
  {
    n: 121,
    name: 'Press Forge 121',
    objective: 'Teach the stamper. Mix the guillotine. Rest between packs. Reach the gate.',
    theme: 'fort',
    featured: 'z',
    mix: 'x',
    silhouette: 'hill-valley',
    setpiece: 'colonnade',
    w: 120,
    land: [{ t: "hill", at: 13, w: 11, h: 2 }, { t: "pass", at: 45, w: 18 }, { t: "pass", at: 72, w: 19 }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 59,
    porchAX: 31,
    porchBX: 87,
    setX: 68,
    pocketX: 97,
    porchA: '89A',
    porchB: '8A9',
    prize: 'i',
  },
  {
    n: 122,
    name: 'Censer Wharf 122',
    objective: 'Teach the swinging censer. Mix the bounce pit. Rest between packs. Reach the gate.',
    theme: 'canal',
    featured: 'l',
    mix: 'T',
    silhouette: 'valley-hill',
    setpiece: 'ice',
    w: 124,
    land: [{ t: "valley", at: 14, w: 12, d: 2 }, { t: "hill", at: 42, w: 13, h: 2 }, { t: "ridge", at: 72, w: 18 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 60,
    porchAX: 32,
    porchBX: 88,
    setX: 70,
    pocketX: 100,
    porchA: 'BCE',
    porchB: 'B9E',
    prize: 'i',
  },
  {
    n: 123,
    name: 'Guillotine Spring 123',
    objective: 'Teach the guillotine. Mix the swinging censer. Rest between packs. Reach the gate.',
    theme: 'coil',
    featured: 'x',
    mix: 'l',
    silhouette: 'twin-hills',
    setpiece: 'dual-loft',
    w: 128,
    land: [{ t: "hill", at: 15, w: 13, h: 2 }, { t: "hill", at: 45, w: 14, h: 1 }, { t: "valley", at: 72, w: 10, d: 2 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 58,
    porchAX: 33,
    porchBX: 89,
    setX: 65,
    pocketX: 103,
    porchA: 'Y75',
    porchB: 'C9Y',
    prize: 'i',
  },
  {
    n: 124,
    name: 'Drop-Cap Folio 124',
    objective: 'Teach the falling drop-cap. Mix the swinging censer. Rest between packs. Reach the gate.',
    theme: 'vault',
    featured: 'f',
    mix: 'l',
    silhouette: 'ridge-pass',
    setpiece: 'court',
    w: 132,
    land: [{ t: "ridge", at: 12, w: 18 }, { t: "pass", at: 42, w: 16 }, { t: "hill", at: 72, w: 11, h: 1 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 59,
    porchAX: 34,
    porchBX: 86,
    setX: 67,
    pocketX: 110,
    porchA: '8A9',
    porchB: 'B2C',
    prize: '$',
  },
  {
    n: 125,
    name: 'Abyss Warden',
    objective: 'Teach the rotor court. Mix the guillotine. Two packs, then the warden. Take the gate.',
    theme: 'abyss',
    featured: 'd',
    mix: 'x',
    silhouette: 'canal-bridge',
    setpiece: 'terrace',
    w: 136,
    land: [{ t: "hill", at: 13, w: 10, h: 2 }, { t: "valley", at: 45, w: 11, d: 2 }, { t: "bridge", at: 72, w: 10, ride: "{" }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 60,
    porchAX: 30,
    porchBX: 87,
    setX: 69,
    pocketX: 113,
    porchA: 'B2C',
    porchB: '!Y8',
    prize: 'i',
  },
  {
    n: 126,
    name: 'Basin Stair 126',
    objective: 'Teach the ink basin. Mix the ember grate. Rest between packs. Reach the gate.',
    theme: 'spire',
    featured: 'w',
    mix: 'j',
    silhouette: 'court-pass',
    setpiece: 'torches',
    w: 104,
    land: [{ t: "valley", at: 14, w: 11, d: 2 }, { t: "valley", at: 42, w: 12, d: 2 }, { t: "pass", at: 72, w: 19 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 58,
    porchAX: 31,
    porchBX: 88,
    setX: 64,
    pocketX: 80,
    porchA: 'E7Y',
    porchB: 'E87',
    prize: 'i',
  },
  {
    n: 127,
    name: 'Grate Orrery 127',
    objective: 'Teach the ember grate. Mix the floor geyser. Rest between packs. Reach the gate.',
    theme: 'orbit',
    featured: 'j',
    mix: 'g',
    silhouette: 'pit-chain',
    setpiece: 'switchback',
    w: 108,
    land: [{ t: "valley", at: 15, w: 12, d: 2 }, { t: "valley", at: 45, w: 13, d: 2 }, { t: "ridge", at: 72, w: 18 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 59,
    porchAX: 32,
    porchBX: 89,
    setX: 66,
    pocketX: 83,
    porchA: '98B',
    porchB: 'E7Y',
    prize: 'i',
  },
  {
    n: 128,
    name: 'Carriage Crevasse 128',
    objective: 'Teach the riding carriage. Mix the echo plate. Rest between packs. Reach the gate.',
    theme: 'glacier',
    featured: '{',
    mix: '[',
    silhouette: 'loft-street',
    setpiece: 'zipper',
    w: 112,
    land: [{ t: "bridge", at: 12, w: 11, ride: "{" }, { t: "hill", at: 42, w: 14, h: 2 }, { t: "hill", at: 72, w: 10, h: 1 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 60,
    porchAX: 33,
    porchBX: 86,
    setX: 68,
    pocketX: 90,
    porchA: 'CA5',
    porchB: 'C75',
    prize: '$',
  },
  {
    n: 129,
    name: 'Echo Sentence 129',
    objective: 'Teach the echo plate. Mix the shutter window. Rest between packs. Reach the gate.',
    theme: 'remainder',
    featured: '[',
    mix: '}',
    silhouette: 'saw-rail',
    setpiece: 'ribs',
    w: 116,
    land: [{ t: "hill", at: 13, w: 14, h: 2 }, { t: "pass", at: 45, w: 16 }, { t: "pass", at: 72, w: 17 }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 58,
    porchAX: 34,
    porchBX: 87,
    setX: 70,
    pocketX: 93,
    porchA: '7YE',
    porchB: 'A9B',
    prize: 'i',
  },
  {
    n: 130,
    name: 'The Last Rib',
    objective: 'Teach the shutter window. Mix the rotor court. Two packs, then the warden. Take the gate.',
    theme: 'street',
    featured: '}',
    mix: 'd',
    silhouette: 'shutter-gallery',
    setpiece: 'vent',
    w: 120,
    land: [{ t: "pass", at: 14, w: 16 }, { t: "hill", at: 42, w: 11, h: 2 }, { t: "ridge", at: 72, w: 16 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 59,
    porchAX: 30,
    porchBX: 88,
    setX: 65,
    pocketX: 96,
    porchA: 'A8C',
    porchB: '!98',
    prize: 'i',
  },
  {
    n: 131,
    name: 'Saw Forge 131',
    objective: 'Teach the hanging saw. Mix the loft laser. Rest between packs. Reach the gate.',
    theme: 'fort',
    featured: 'S',
    mix: '|',
    silhouette: 'echo-lofts',
    setpiece: 'colonnade',
    w: 124,
    land: [{ t: "ridge", at: 15, w: 15 }, { t: "pass", at: 45, w: 18 }, { t: "valley", at: 72, w: 13, d: 2 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 60,
    porchAX: 31,
    porchBX: 89,
    setX: 67,
    pocketX: 99,
    porchA: 'B9E',
    porchB: '9BE',
    prize: 'i',
  },
  {
    n: 132,
    name: 'Lift Wharf 132',
    objective: 'Teach the lift shaft. Mix the blink pad. Rest between packs. Reach the gate.',
    theme: 'canal',
    featured: '`',
    mix: ')',
    silhouette: 'carriage-canyon',
    setpiece: 'ice',
    w: 128,
    land: [{ t: "valley", at: 12, w: 12, d: 2 }, { t: "valley", at: 42, w: 13, d: 2 }, { t: "hill", at: 72, w: 14, h: 1 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 58,
    porchAX: 32,
    porchBX: 86,
    setX: 69,
    pocketX: 106,
    porchA: 'Y8A',
    porchB: '89A',
    prize: '$',
  },
  {
    n: 133,
    name: 'Geyser Spring 133',
    objective: 'Teach the floor geyser. Mix the lift shaft. Rest between packs. Reach the gate.',
    theme: 'coil',
    featured: 'g',
    mix: '`',
    silhouette: 'laser-nave',
    setpiece: 'dual-loft',
    w: 132,
    land: [{ t: "valley", at: 13, w: 13, d: 2 }, { t: "valley", at: 45, w: 14, d: 2 }, { t: "pass", at: 72, w: 16 }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 59,
    porchAX: 33,
    porchBX: 87,
    setX: 64,
    pocketX: 109,
    porchA: 'C75',
    porchB: 'CA5',
    prize: 'i',
  },
  {
    n: 134,
    name: 'Blink Folio 134',
    objective: 'Teach the blink pad. Mix the hanging saw. Rest between packs. Reach the gate.',
    theme: 'vault',
    featured: ')',
    mix: 'S',
    silhouette: 'geyser-row',
    setpiece: 'court',
    w: 136,
    land: [{ t: "valley", at: 14, w: 14, d: 2 }, { t: "ridge", at: 42, w: 14 }, { t: "ridge", at: 72, w: 15 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 60,
    porchAX: 34,
    porchBX: 88,
    setX: 66,
    pocketX: 112,
    porchA: '9BE',
    porchB: 'A7C',
    prize: 'i',
  },
  {
    n: 135,
    name: 'Spire Warden',
    objective: 'Teach the loft laser. Mix the belt slope. Two packs, then the warden. Take the gate.',
    theme: 'abyss',
    featured: '|',
    mix: '/',
    silhouette: 'rotor-court',
    setpiece: 'terrace',
    w: 104,
    land: [{ t: "pass", at: 15, w: 16 }, { t: "hill", at: 45, w: 11, h: 1 }, { t: "valley", at: 72, w: 12, d: 2 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 58,
    porchAX: 30,
    porchBX: 89,
    setX: 68,
    pocketX: 79,
    porchA: 'A7C',
    porchB: '!BC',
    prize: 'i',
  },
  {
    n: 136,
    name: 'Belt Stair 136',
    objective: 'Teach the belt slope. Mix the crumble run. Rest between packs. Reach the gate.',
    theme: 'spire',
    featured: '/',
    mix: '-',
    silhouette: 'ice-shelf',
    setpiece: 'torches',
    w: 108,
    land: [{ t: "hill", at: 12, w: 11, h: 1 }, { t: "hill", at: 42, w: 12, h: 2 }, { t: "valley", at: 72, w: 13, d: 2 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 59,
    porchAX: 31,
    porchBX: 86,
    setX: 70,
    pocketX: 86,
    porchA: '8YE',
    porchB: '7YE',
    prize: '$',
  },
  {
    n: 137,
    name: 'Bounce Orrery 137',
    objective: 'Teach the bounce pit. Mix the belt slope. Rest between packs. Reach the gate.',
    theme: 'orbit',
    featured: 'T',
    mix: '/',
    silhouette: 'rib-climb',
    setpiece: 'switchback',
    w: 112,
    land: [{ t: "valley", at: 13, w: 12, d: 2 }, { t: "hill", at: 45, w: 13, h: 1 }, { t: "pass", at: 72, w: 20 }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 60,
    porchAX: 32,
    porchBX: 87,
    setX: 65,
    pocketX: 89,
    porchA: 'B5A',
    porchB: '8YE',
    prize: 'i',
  },
  {
    n: 138,
    name: 'Crumble Crevasse 138',
    objective: 'Teach the crumble run. Mix the bounce pit. Rest between packs. Reach the gate.',
    theme: 'glacier',
    featured: '-',
    mix: 'T',
    silhouette: 'mixed-sentence',
    setpiece: 'zipper',
    w: 116,
    land: [{ t: "hill", at: 14, w: 13, h: 1 }, { t: "valley", at: 42, w: 14, d: 2 }, { t: "ridge", at: 72, w: 14 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 58,
    porchAX: 33,
    porchBX: 88,
    setX: 67,
    pocketX: 92,
    porchA: 'C9Y',
    porchB: 'Y75',
    prize: 'i',
  },
  {
    n: 139,
    name: 'Loft Sentence 139',
    objective: 'Teach the loft street. Mix the crumble run. Rest between packs. Reach the gate.',
    theme: 'remainder',
    featured: '=',
    mix: '-',
    silhouette: 'pass-court-pass',
    setpiece: 'ribs',
    w: 120,
    land: [{ t: "hill", at: 15, w: 14, h: 2 }, { t: "hill", at: 45, w: 10, h: 1 }, { t: "valley", at: 72, w: 11, d: 2 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 59,
    porchAX: 34,
    porchBX: 89,
    setX: 69,
    pocketX: 95,
    porchA: 'E87',
    porchB: 'A8C',
    prize: 'i',
  },
  {
    n: 140,
    name: 'The Written Height',
    objective: 'Teach the swinging censer. Mix the bounce pit. Two packs, then the warden. Take the gate.',
    theme: 'street',
    featured: 'l',
    mix: 'T',
    silhouette: 'well-loft-well',
    setpiece: 'vent',
    w: 124,
    land: [{ t: "hill", at: 12, w: 10, h: 1 }, { t: "valley", at: 42, w: 11, d: 2 }, { t: "valley", at: 72, w: 12, d: 2 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 60,
    porchAX: 30,
    porchBX: 86,
    setX: 64,
    pocketX: 102,
    porchA: 'A9B',
    porchB: '!B5',
    prize: '$',
  },
  {
    n: 141,
    name: 'Press Forge 141',
    objective: 'Teach the stamper. Mix the swinging censer. Rest between packs. Reach the gate.',
    theme: 'fort',
    featured: 'z',
    mix: 'l',
    silhouette: 'hill-valley',
    setpiece: 'colonnade',
    w: 128,
    land: [{ t: "hill", at: 13, w: 11, h: 2 }, { t: "hill", at: 45, w: 12, h: 1 }, { t: "pass", at: 72, w: 19 }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 58,
    porchAX: 31,
    porchBX: 87,
    setX: 66,
    pocketX: 105,
    porchA: '89A',
    porchB: '8A9',
    prize: 'i',
  },
  {
    n: 142,
    name: 'Censer Wharf 142',
    objective: 'Teach the swinging censer. Mix the sluice (mix only). Rest between packs. Reach the gate.',
    theme: 'canal',
    featured: 'l',
    mix: '~',
    silhouette: 'valley-hill',
    setpiece: 'ice',
    w: 132,
    land: [{ t: "valley", at: 14, w: 12, d: 2 }, { t: "hill", at: 42, w: 13, h: 2 }, { t: "ridge", at: 72, w: 18 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 59,
    porchAX: 32,
    porchBX: 88,
    setX: 68,
    pocketX: 108,
    porchA: 'BCE',
    porchB: 'B9E',
    prize: 'i',
  },
  {
    n: 143,
    name: 'Guillotine Spring 143',
    objective: 'Teach the guillotine. Mix the loft laser. Rest between packs. Reach the gate.',
    theme: 'coil',
    featured: 'x',
    mix: '|',
    silhouette: 'twin-hills',
    setpiece: 'dual-loft',
    w: 136,
    land: [{ t: "hill", at: 15, w: 13, h: 2 }, { t: "hill", at: 45, w: 14, h: 1 }, { t: "valley", at: 72, w: 10, d: 2 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 60,
    porchAX: 33,
    porchBX: 89,
    setX: 70,
    pocketX: 111,
    porchA: 'Y75',
    porchB: 'C9Y',
    prize: 'i',
  },
  {
    n: 144,
    name: 'Drop-Cap Folio 144',
    objective: 'Teach the falling drop-cap. Mix the stamper. Rest between packs. Reach the gate.',
    theme: 'vault',
    featured: 'f',
    mix: 'z',
    silhouette: 'ridge-pass',
    setpiece: 'court',
    w: 104,
    land: [{ t: "ridge", at: 12, w: 18 }, { t: "pass", at: 42, w: 16 }, { t: "hill", at: 72, w: 11, h: 1 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 58,
    porchAX: 34,
    porchBX: 86,
    setX: 65,
    pocketX: 82,
    porchA: '8A9',
    porchB: 'B2C',
    prize: '$',
  },
  {
    n: 145,
    name: 'Vault Warden',
    objective: 'Teach the rotor court. Mix the echo plate. Two packs, then the warden. Take the gate.',
    theme: 'abyss',
    featured: 'd',
    mix: '[',
    silhouette: 'canal-bridge',
    setpiece: 'terrace',
    w: 108,
    land: [{ t: "hill", at: 13, w: 10, h: 2 }, { t: "valley", at: 45, w: 11, d: 2 }, { t: "bridge", at: 72, w: 10, ride: "{" }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 59,
    porchAX: 30,
    porchBX: 87,
    setX: 67,
    pocketX: 85,
    porchA: 'B2C',
    porchB: '!Y8',
    prize: 'i',
  },
  {
    n: 146,
    name: 'Basin Stair 146',
    objective: 'Teach the ink basin. Mix the bounce pit. Rest between packs. Reach the gate.',
    theme: 'spire',
    featured: 'w',
    mix: 'T',
    silhouette: 'court-pass',
    setpiece: 'torches',
    w: 112,
    land: [{ t: "valley", at: 14, w: 11, d: 2 }, { t: "valley", at: 42, w: 12, d: 2 }, { t: "pass", at: 72, w: 19 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 60,
    porchAX: 31,
    porchBX: 88,
    setX: 69,
    pocketX: 88,
    porchA: 'E7Y',
    porchB: 'E87',
    prize: 'i',
  },
  {
    n: 147,
    name: 'Grate Orrery 147',
    objective: 'Teach the ember grate. Mix the ink basin. Rest between packs. Reach the gate.',
    theme: 'orbit',
    featured: 'j',
    mix: 'w',
    silhouette: 'pit-chain',
    setpiece: 'switchback',
    w: 116,
    land: [{ t: "valley", at: 15, w: 12, d: 2 }, { t: "valley", at: 45, w: 13, d: 2 }, { t: "ridge", at: 72, w: 18 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 58,
    porchAX: 32,
    porchBX: 89,
    setX: 64,
    pocketX: 91,
    porchA: '98B',
    porchB: 'E7Y',
    prize: 'i',
  },
  {
    n: 148,
    name: 'Carriage Crevasse 148',
    objective: 'Teach the riding carriage. Mix the blink pad. Rest between packs. Reach the gate.',
    theme: 'glacier',
    featured: '{',
    mix: ')',
    silhouette: 'loft-street',
    setpiece: 'zipper',
    w: 120,
    land: [{ t: "bridge", at: 12, w: 11, ride: "{" }, { t: "valley", at: 42, w: 14, d: 2 }, { t: "hill", at: 72, w: 10, h: 1 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 59,
    porchAX: 33,
    porchBX: 86,
    setX: 66,
    pocketX: 98,
    porchA: 'CA5',
    porchB: 'C75',
    prize: '$',
  },
  {
    n: 149,
    name: 'Echo Sentence 149',
    objective: 'Teach the echo plate. Mix the loft street. Rest between packs. Reach the gate.',
    theme: 'remainder',
    featured: '[',
    mix: '=',
    silhouette: 'saw-rail',
    setpiece: 'ribs',
    w: 124,
    land: [{ t: "hill", at: 13, w: 14, h: 2 }, { t: "hill", at: 45, w: 10, h: 1 }, { t: "pass", at: 72, w: 17 }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 60,
    porchAX: 34,
    porchBX: 87,
    setX: 68,
    pocketX: 101,
    porchA: '7YE',
    porchB: 'A9B',
    prize: 'i',
  },
  {
    n: 150,
    name: 'The Closed Folio',
    objective: 'Teach the shutter window. Mix the guillotine. Two packs, then the warden. Take the gate.',
    theme: 'street',
    featured: '}',
    mix: 'x',
    silhouette: 'shutter-gallery',
    setpiece: 'vent',
    w: 128,
    land: [{ t: "pass", at: 14, w: 16 }, { t: "pass", at: 42, w: 17 }, { t: "ridge", at: 72, w: 16 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 58,
    porchAX: 30,
    porchBX: 88,
    setX: 70,
    pocketX: 104,
    porchA: 'A8C',
    porchB: '!98',
    prize: 'i',
  },
  {
    n: 151,
    name: 'Saw Forge 151',
    objective: 'Teach the hanging saw. Mix the blink pad. Rest between packs. Reach the gate.',
    theme: 'fort',
    featured: 'S',
    mix: ')',
    silhouette: 'echo-lofts',
    setpiece: 'colonnade',
    w: 132,
    land: [{ t: "ridge", at: 15, w: 15 }, { t: "valley", at: 45, w: 12, d: 2 }, { t: "valley", at: 72, w: 13, d: 2 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 59,
    porchAX: 31,
    porchBX: 89,
    setX: 65,
    pocketX: 107,
    porchA: 'B9E',
    porchB: '9BE',
    prize: 'i',
  },
  {
    n: 152,
    name: 'Lift Wharf 152',
    objective: 'Teach the lift shaft. Mix the bounce pit. Rest between packs. Reach the gate.',
    theme: 'canal',
    featured: '`',
    mix: 'T',
    silhouette: 'carriage-canyon',
    setpiece: 'ice',
    w: 136,
    land: [{ t: "valley", at: 12, w: 12, d: 2 }, { t: "valley", at: 42, w: 13, d: 2 }, { t: "hill", at: 72, w: 14, h: 1 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 60,
    porchAX: 32,
    porchBX: 86,
    setX: 67,
    pocketX: 114,
    porchA: 'Y8A',
    porchB: '89A',
    prize: '$',
  },
  {
    n: 153,
    name: 'Geyser Spring 153',
    objective: 'Teach the floor geyser. Mix the ink basin. Rest between packs. Reach the gate.',
    theme: 'coil',
    featured: 'g',
    mix: 'w',
    silhouette: 'laser-nave',
    setpiece: 'dual-loft',
    w: 104,
    land: [{ t: "valley", at: 13, w: 13, d: 2 }, { t: "valley", at: 45, w: 14, d: 2 }, { t: "pass", at: 72, w: 16 }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 58,
    porchAX: 33,
    porchBX: 87,
    setX: 69,
    pocketX: 81,
    porchA: 'C75',
    porchB: 'CA5',
    prize: 'i',
  },
  {
    n: 154,
    name: 'Blink Folio 154',
    objective: 'Teach the blink pad. Mix the bounce pit. Rest between packs. Reach the gate.',
    theme: 'vault',
    featured: ')',
    mix: 'T',
    silhouette: 'geyser-row',
    setpiece: 'court',
    w: 108,
    land: [{ t: "valley", at: 14, w: 14, d: 2 }, { t: "valley", at: 42, w: 10, d: 2 }, { t: "ridge", at: 72, w: 15 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 59,
    porchAX: 34,
    porchBX: 88,
    setX: 64,
    pocketX: 84,
    porchA: '9BE',
    porchB: 'A7C',
    prize: 'i',
  },
  {
    n: 155,
    name: 'The Plus Gate',
    objective: 'Teach the loft laser. Mix the guillotine. Two packs, then the warden. Take the gate.',
    theme: 'abyss',
    featured: '|',
    mix: 'x',
    silhouette: 'rotor-court',
    setpiece: 'terrace',
    w: 112,
    land: [{ t: "pass", at: 15, w: 16 }, { t: "pass", at: 45, w: 17 }, { t: "valley", at: 72, w: 12, d: 2 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 60,
    porchAX: 30,
    porchBX: 89,
    setX: 66,
    pocketX: 87,
    porchA: 'A7C',
    porchB: '!BC',
    prize: 'i',
  },
  {
    n: 156,
    name: 'Belt Stair 156',
    objective: 'Teach the belt slope. Mix the bounce pit. Rest between packs. Reach the gate.',
    theme: 'spire',
    featured: '/',
    mix: 'T',
    silhouette: 'ice-shelf',
    setpiece: 'torches',
    w: 116,
    land: [{ t: "hill", at: 12, w: 11, h: 1 }, { t: "valley", at: 42, w: 12, d: 2 }, { t: "valley", at: 72, w: 13, d: 2 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 58,
    porchAX: 31,
    porchBX: 86,
    setX: 68,
    pocketX: 94,
    porchA: '8YE',
    porchB: '7YE',
    prize: '$',
  },
  {
    n: 157,
    name: 'Bounce Orrery 157',
    objective: 'Teach the bounce pit. Mix the loft street. Rest between packs. Reach the gate.',
    theme: 'orbit',
    featured: 'T',
    mix: '=',
    silhouette: 'rib-climb',
    setpiece: 'switchback',
    w: 120,
    land: [{ t: "valley", at: 13, w: 12, d: 2 }, { t: "hill", at: 45, w: 13, h: 1 }, { t: "pass", at: 72, w: 20 }],
    teachX: 15,
    mixX: 47,
    extraX: 74,
    restX: 59,
    porchAX: 32,
    porchBX: 87,
    setX: 70,
    pocketX: 97,
    porchA: 'B5A',
    porchB: '8YE',
    prize: 'i',
  },
  {
    n: 158,
    name: 'Crumble Crevasse 158',
    objective: 'Teach the crumble run. Mix the lift shaft. Rest between packs. Reach the gate.',
    theme: 'glacier',
    featured: '-',
    mix: '`',
    silhouette: 'mixed-sentence',
    setpiece: 'zipper',
    w: 124,
    land: [{ t: "hill", at: 14, w: 13, h: 1 }, { t: "valley", at: 42, w: 14, d: 2 }, { t: "ridge", at: 72, w: 14 }],
    teachX: 16,
    mixX: 44,
    extraX: 74,
    restX: 60,
    porchAX: 33,
    porchBX: 88,
    setX: 65,
    pocketX: 100,
    porchA: 'C9Y',
    porchB: 'Y75',
    prize: 'i',
  },
  {
    n: 159,
    name: 'Loft Sentence 159',
    objective: 'Teach the loft street. Mix the loft laser. Rest between packs. Reach the gate.',
    theme: 'remainder',
    featured: '=',
    mix: '|',
    silhouette: 'pass-court-pass',
    setpiece: 'ribs',
    w: 128,
    land: [{ t: "hill", at: 15, w: 14, h: 2 }, { t: "pass", at: 45, w: 16 }, { t: "valley", at: 72, w: 11, d: 2 }],
    teachX: 17,
    mixX: 47,
    extraX: 74,
    restX: 58,
    porchAX: 34,
    porchBX: 89,
    setX: 67,
    pocketX: 103,
    porchA: 'E87',
    porchB: 'A8C',
    prize: 'i',
  },
  {
    n: 160,
    name: 'The Second Remainder',
    objective: 'Teach the swinging censer. Mix the guillotine. Two packs, then the warden. Take the gate.',
    theme: 'street',
    featured: 'l',
    mix: 'x',
    silhouette: 'well-loft-well',
    setpiece: 'vent',
    w: 132,
    land: [{ t: "hill", at: 12, w: 10, h: 1 }, { t: "pass", at: 42, w: 17 }, { t: "valley", at: 72, w: 12, d: 2 }],
    teachX: 14,
    mixX: 44,
    extraX: 74,
    restX: 59,
    porchAX: 30,
    porchBX: 86,
    setX: 69,
    pocketX: 110,
    porchA: 'A9B',
    porchB: '!B5',
    prize: '$',
  },
];

export function centurySpec(n: number): CenturySpec | undefined {
  return CENTURY[n - 61];
}

