/** Unique Remainder ledger titles. Index matches stage number. */
export const REMAINDER_NAMES: Record<number, string> = {
  6: "Open Case",
  7: "Ink Dock",
  8: "Ash Column",
  9: "Iris Sluice",
  10: "The Brace",
  11: "Foundry Arch",
  12: "Spark Coil",
  13: "Type Machines",
  14: "Ember Fort",
  15: "Book Warden",
  16: "Lower Ribs",
  17: "Column Street",
  18: "Rain Ships",
  19: "Petal Court",
  20: "The Spire",
  21: "Iris Spire",
  22: "Aurora Shaft",
  23: "Red Dock",
  24: "Machine Fort",
  25: "The Coil",
  26: "Static Mirror",
  27: "Ash Arch",
  28: "Count Ribs",
  29: "Quiet Spire",
  30: "The Period",
  31: "Gold Orrery",
  32: "Night Lattice",
  33: "White Margin",
  34: "Ember Script",
  35: "The Circumflex",
  36: "Hail Glass",
  37: "Storm Script",
  38: "Day Garden",
  39: "High Ice",
  40: "Void Point",
  41: "Teal Orrery",
  42: "Ink Garden",
  43: "Rime Lattice",
  44: "Aurora Spire",
  45: "Foundry Script",
  46: "Mirror Void",
  47: "Packed Ice",
  48: "Lightning Rule",
  49: "Gold Script",
  50: "Glass Vault",
  51: "Static Remainder",
  52: "Hail Lattice",
  53: "Garden Aurora",
  54: "Ribs of the Count",
  55: "Gold Remainder",
  56: "White Glass",
  57: "Lightning Orrery",
  58: "Ember Lattice",
  59: "Mirror Night",
  60: "The Remainder",
};

export const REMAINDER_OBJECTIVES: Record<number, string> = {
  6: "First unbound hall. Bounce the case, reach the gate.",
  7: "Wet road. Bounce the dock, take the check.",
  8: "Rise through ash. The loft is optional.",
  9: "Cross the sluice. Teeth under the gap.",
  10: "Warden in the petal vault. Clear it, take the gate.",
  11: "Crumble the arch. Ember loft, then the gate.",
  12: "Bounce the coil. Sparks are scenery.",
  13: "Mix bounce and shelf through the machines.",
  14: "Last crumble before the laser. Rest at the check.",
  15: "Lasers hang off the floor. Clear the warden.",
  16: "Ride the rib, then the laser. Pocket is optional.",
  17: "Belt and bounce. Columns are landmarks.",
  18: "Belt the wet road. Ships in the mid.",
  19: "Mix laser and shelf. Rest before the spire.",
  20: "Aurora shaft. Clear the warden.",
  21: "Climb the iris. Laser off the stair.",
  22: "Two known verbs, then the gate.",
  23: "Wet belt, then rest.",
  24: "Last fort before the coil warden.",
  25: "Lift and geyser unlock. Clear the warden.",
  26: "Blink the mirror. Wait-spot on stone.",
  27: "Geyser the ash, then the loft.",
  28: "Climb the ribs. Vent is optional.",
  29: "Last stair before The Period.",
  30: "End-Mark waits in the vault. Close the first book.",
  31: "Lift the gold ring. An optional loft holds a secret.",
  32: "Wait the blink, then fold the night lattice.",
  33: "Ride the white rail. Bounce the margin trench.",
  34: "Take the ember geyser. Read the first heat.",
  35: "The circumflex hangs. Clear the warden.",
  36: "Hail on glass. Time the blink, then rest on the loft.",
  37: "Storm script. The letters still bite.",
  38: "Day garden. Mix lift and blink, rest in the sun loft.",
  39: "High ice. A glacier step, then the gate.",
  40: "A void point. Clear the warden, take the gate.",
  41: "Teal rings turn. Lift, then keep walking.",
  42: "Ink garden. Wet road or dry loft — they meet at the check.",
  43: "Rime lattice. Ride the rail through the hail.",
  44: "Climb the aurora stair. Lasers hang off the floor.",
  45: "The foundry still sets type in fire. Clear the warden.",
  46: "Mirror void. A dark orbit with a known toy.",
  47: "Packed ice. Tight rail, short commit.",
  48: "Blink, then the saw. Rest immediately after.",
  49: "Gold script. Two known verbs, then the gate.",
  50: "Glass vault. The count is thinner here.",
  51: "High road holds the secret. Low road holds the fight.",
  52: "Hail lattice. Ice under a late sky.",
  53: "Garden aurora. Rings again, quieter.",
  54: "Climb the ribs. The vent is optional.",
  55: "Gold remainder. One more warden before the last page.",
  56: "White glass. A last ice hall.",
  57: "Lift into the laser, then the recovery shelf.",
  58: "Ember lattice. Known heat, known teeth.",
  59: "Same blink as night lattice. The pocket is on the far side.",
  60: "The last ledger. Blink, saw, geyser, lift — then the Remainder. Take the FINAL gate.",
};

export function remainderName(n: number, boss: boolean) {
  return REMAINDER_NAMES[n] ?? (boss ? `Warden ${n}` : `Ledger ${n}`);
}

export function remainderObjective(n: number, boss: boolean) {
  return REMAINDER_OBJECTIVES[n] ?? (boss ? "Clear the warden. Take the gate." : "Cross this remainder. Reach the gate.");
}
