/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlmanacRouteImport } from './routes/almanac'
import { Route as ArchetypesRouteImport } from './routes/archetypes'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as BondRouteImport } from './routes/bond'
import { Route as CircleRouteImport } from './routes/circle'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as CountRouteImport } from './routes/count'
import { Route as DoctrineRouteImport } from './routes/doctrine'
import { Route as HouseRouteImport } from './routes/house'
import { Route as KeyRouteImport } from './routes/key'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StoicheiaRouteImport } from './routes/stoicheia'
import { Route as ApiCardRouteImport } from './routes/api/card'
import { Route as OgFileRouteImport } from './routes/og.$file'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as StoicheiaIndexRouteImport } from './routes/stoicheia.index'
import { Route as StoicheiaCalendarRouteImport } from './routes/stoicheia.calendar'
import { Route as StoicheiaDoctrineRouteImport } from './routes/stoicheia.doctrine'
import { Route as StoicheiaHoraeRouteImport } from './routes/stoicheia.horae'
import { Route as StoicheiaHymnRouteImport } from './routes/stoicheia.hymn'
import { Route as StoicheiaIsopsephyRouteImport } from './routes/stoicheia.isopsephy'
import { Route as StoicheiaXeniaRouteImport } from './routes/stoicheia.xenia'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmanacRoute = AlmanacRouteImport.update({
  id: '/almanac',
  path: '/almanac',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchetypesRoute = ArchetypesRouteImport.update({
  id: '/archetypes',
  path: '/archetypes',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const BondRoute = BondRouteImport.update({
  id: '/bond',
  path: '/bond',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleRoute = CircleRouteImport.update({
  id: '/circle',
  path: '/circle',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const CountRoute = CountRouteImport.update({
  id: '/count',
  path: '/count',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctrineRoute = DoctrineRouteImport.update({
  id: '/doctrine',
  path: '/doctrine',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseRoute = HouseRouteImport.update({
  id: '/house',
  path: '/house',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyRoute = KeyRouteImport.update({
  id: '/key',
  path: '/key',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StoicheiaRoute = StoicheiaRouteImport.update({
  id: '/stoicheia',
  path: '/stoicheia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCardRoute = ApiCardRouteImport.update({
  id: '/api/card',
  path: '/api/card',
  getParentRoute: () => rootRouteImport,
} as any)
const OgFileRoute = OgFileRouteImport.update({
  id: '/og/$file',
  path: '/og/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoicheiaIndexRoute = StoicheiaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoicheiaRoute,
} as any)
const StoicheiaCalendarRoute = StoicheiaCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StoicheiaRoute,
} as any)
const StoicheiaDoctrineRoute = StoicheiaDoctrineRouteImport.update({
  id: '/doctrine',
  path: '/doctrine',
  getParentRoute: () => StoicheiaRoute,
} as any)
const StoicheiaHoraeRoute = StoicheiaHoraeRouteImport.update({
  id: '/horae',
  path: '/horae',
  getParentRoute: () => StoicheiaRoute,
} as any)
const StoicheiaHymnRoute = StoicheiaHymnRouteImport.update({
  id: '/hymn',
  path: '/hymn',
  getParentRoute: () => StoicheiaRoute,
} as any)
const StoicheiaIsopsephyRoute = StoicheiaIsopsephyRouteImport.update({
  id: '/isopsephy',
  path: '/isopsephy',
  getParentRoute: () => StoicheiaRoute,
} as any)
const StoicheiaXeniaRoute = StoicheiaXeniaRouteImport.update({
  id: '/xenia',
  path: '/xenia',
  getParentRoute: () => StoicheiaRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/almanac': typeof AlmanacRoute
  '/archetypes': typeof ArchetypesRoute
  '/atlas': typeof AtlasRoute
  '/bond': typeof BondRoute
  '/circle': typeof CircleRoute
  '/claim': typeof ClaimRoute
  '/count': typeof CountRoute
  '/doctrine': typeof DoctrineRoute
  '/house': typeof HouseRoute
  '/key': typeof KeyRoute
  '/login': typeof LoginRoute
  '/stoicheia': typeof StoicheiaRouteWithChildren
  '/api/card': typeof ApiCardRoute
  '/og/$file': typeof OgFileRoute
  '/p/$slug': typeof PSlugRoute
  '/stoicheia/calendar': typeof StoicheiaCalendarRoute
  '/stoicheia/doctrine': typeof StoicheiaDoctrineRoute
  '/stoicheia/horae': typeof StoicheiaHoraeRoute
  '/stoicheia/hymn': typeof StoicheiaHymnRoute
  '/stoicheia/isopsephy': typeof StoicheiaIsopsephyRoute
  '/stoicheia/xenia': typeof StoicheiaXeniaRoute
  '/stoicheia/': typeof StoicheiaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/almanac': typeof AlmanacRoute
  '/archetypes': typeof ArchetypesRoute
  '/atlas': typeof AtlasRoute
  '/bond': typeof BondRoute
  '/circle': typeof CircleRoute
  '/claim': typeof ClaimRoute
  '/count': typeof CountRoute
  '/doctrine': typeof DoctrineRoute
  '/house': typeof HouseRoute
  '/key': typeof KeyRoute
  '/login': typeof LoginRoute
  '/api/card': typeof ApiCardRoute
  '/og/$file': typeof OgFileRoute
  '/p/$slug': typeof PSlugRoute
  '/stoicheia/calendar': typeof StoicheiaCalendarRoute
  '/stoicheia/doctrine': typeof StoicheiaDoctrineRoute
  '/stoicheia/horae': typeof StoicheiaHoraeRoute
  '/stoicheia/hymn': typeof StoicheiaHymnRoute
  '/stoicheia/isopsephy': typeof StoicheiaIsopsephyRoute
  '/stoicheia/xenia': typeof StoicheiaXeniaRoute
  '/stoicheia': typeof StoicheiaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/almanac': typeof AlmanacRoute
  '/archetypes': typeof ArchetypesRoute
  '/atlas': typeof AtlasRoute
  '/bond': typeof BondRoute
  '/circle': typeof CircleRoute
  '/claim': typeof ClaimRoute
  '/count': typeof CountRoute
  '/doctrine': typeof DoctrineRoute
  '/house': typeof HouseRoute
  '/key': typeof KeyRoute
  '/login': typeof LoginRoute
  '/stoicheia': typeof StoicheiaRouteWithChildren
  '/api/card': typeof ApiCardRoute
  '/og/$file': typeof OgFileRoute
  '/p/$slug': typeof PSlugRoute
  '/stoicheia/calendar': typeof StoicheiaCalendarRoute
  '/stoicheia/doctrine': typeof StoicheiaDoctrineRoute
  '/stoicheia/horae': typeof StoicheiaHoraeRoute
  '/stoicheia/hymn': typeof StoicheiaHymnRoute
  '/stoicheia/isopsephy': typeof StoicheiaIsopsephyRoute
  '/stoicheia/xenia': typeof StoicheiaXeniaRoute
  '/stoicheia/': typeof StoicheiaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/almanac'
    | '/archetypes'
    | '/atlas'
    | '/bond'
    | '/circle'
    | '/claim'
    | '/count'
    | '/doctrine'
    | '/house'
    | '/key'
    | '/login'
    | '/stoicheia'
    | '/api/card'
    | '/og/$file'
    | '/p/$slug'
    | '/stoicheia/calendar'
    | '/stoicheia/doctrine'
    | '/stoicheia/horae'
    | '/stoicheia/hymn'
    | '/stoicheia/isopsephy'
    | '/stoicheia/xenia'
    | '/stoicheia/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/almanac'
    | '/archetypes'
    | '/atlas'
    | '/bond'
    | '/circle'
    | '/claim'
    | '/count'
    | '/doctrine'
    | '/house'
    | '/key'
    | '/login'
    | '/api/card'
    | '/og/$file'
    | '/p/$slug'
    | '/stoicheia/calendar'
    | '/stoicheia/doctrine'
    | '/stoicheia/horae'
    | '/stoicheia/hymn'
    | '/stoicheia/isopsephy'
    | '/stoicheia/xenia'
    | '/stoicheia'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/almanac'
    | '/archetypes'
    | '/atlas'
    | '/bond'
    | '/circle'
    | '/claim'
    | '/count'
    | '/doctrine'
    | '/house'
    | '/key'
    | '/login'
    | '/stoicheia'
    | '/api/card'
    | '/og/$file'
    | '/p/$slug'
    | '/stoicheia/calendar'
    | '/stoicheia/doctrine'
    | '/stoicheia/horae'
    | '/stoicheia/hymn'
    | '/stoicheia/isopsephy'
    | '/stoicheia/xenia'
    | '/stoicheia/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlmanacRoute: typeof AlmanacRoute
  ArchetypesRoute: typeof ArchetypesRoute
  AtlasRoute: typeof AtlasRoute
  BondRoute: typeof BondRoute
  CircleRoute: typeof CircleRoute
  ClaimRoute: typeof ClaimRoute
  CountRoute: typeof CountRoute
  DoctrineRoute: typeof DoctrineRoute
  HouseRoute: typeof HouseRoute
  KeyRoute: typeof KeyRoute
  LoginRoute: typeof LoginRoute
  StoicheiaRoute: typeof StoicheiaRouteWithChildren
  ApiCardRoute: typeof ApiCardRoute
  OgFileRoute: typeof OgFileRoute
  PSlugRoute: typeof PSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almanac': {
      id: '/almanac'
      path: '/almanac'
      fullPath: '/almanac'
      preLoaderRoute: typeof AlmanacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archetypes': {
      id: '/archetypes'
      path: '/archetypes'
      fullPath: '/archetypes'
      preLoaderRoute: typeof ArchetypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bond': {
      id: '/bond'
      path: '/bond'
      fullPath: '/bond'
      preLoaderRoute: typeof BondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle': {
      id: '/circle'
      path: '/circle'
      fullPath: '/circle'
      preLoaderRoute: typeof CircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/count': {
      id: '/count'
      path: '/count'
      fullPath: '/count'
      preLoaderRoute: typeof CountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctrine': {
      id: '/doctrine'
      path: '/doctrine'
      fullPath: '/doctrine'
      preLoaderRoute: typeof DoctrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house': {
      id: '/house'
      path: '/house'
      fullPath: '/house'
      preLoaderRoute: typeof HouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/key': {
      id: '/key'
      path: '/key'
      fullPath: '/key'
      preLoaderRoute: typeof KeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stoicheia': {
      id: '/stoicheia'
      path: '/stoicheia'
      fullPath: '/stoicheia'
      preLoaderRoute: typeof StoicheiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/card': {
      id: '/api/card'
      path: '/api/card'
      fullPath: '/api/card'
      preLoaderRoute: typeof ApiCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/$file': {
      id: '/og/$file'
      path: '/og/$file'
      fullPath: '/og/$file'
      preLoaderRoute: typeof OgFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stoicheia/': {
      id: '/stoicheia/'
      path: '/'
      fullPath: '/stoicheia/'
      preLoaderRoute: typeof StoicheiaIndexRouteImport
      parentRoute: typeof StoicheiaRoute
    }
    '/stoicheia/calendar': {
      id: '/stoicheia/calendar'
      path: '/calendar'
      fullPath: '/stoicheia/calendar'
      preLoaderRoute: typeof StoicheiaCalendarRouteImport
      parentRoute: typeof StoicheiaRoute
    }
    '/stoicheia/doctrine': {
      id: '/stoicheia/doctrine'
      path: '/doctrine'
      fullPath: '/stoicheia/doctrine'
      preLoaderRoute: typeof StoicheiaDoctrineRouteImport
      parentRoute: typeof StoicheiaRoute
    }
    '/stoicheia/horae': {
      id: '/stoicheia/horae'
      path: '/horae'
      fullPath: '/stoicheia/horae'
      preLoaderRoute: typeof StoicheiaHoraeRouteImport
      parentRoute: typeof StoicheiaRoute
    }
    '/stoicheia/hymn': {
      id: '/stoicheia/hymn'
      path: '/hymn'
      fullPath: '/stoicheia/hymn'
      preLoaderRoute: typeof StoicheiaHymnRouteImport
      parentRoute: typeof StoicheiaRoute
    }
    '/stoicheia/isopsephy': {
      id: '/stoicheia/isopsephy'
      path: '/isopsephy'
      fullPath: '/stoicheia/isopsephy'
      preLoaderRoute: typeof StoicheiaIsopsephyRouteImport
      parentRoute: typeof StoicheiaRoute
    }
    '/stoicheia/xenia': {
      id: '/stoicheia/xenia'
      path: '/xenia'
      fullPath: '/stoicheia/xenia'
      preLoaderRoute: typeof StoicheiaXeniaRouteImport
      parentRoute: typeof StoicheiaRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StoicheiaRouteChildren {
  StoicheiaCalendarRoute: typeof StoicheiaCalendarRoute
  StoicheiaDoctrineRoute: typeof StoicheiaDoctrineRoute
  StoicheiaHoraeRoute: typeof StoicheiaHoraeRoute
  StoicheiaHymnRoute: typeof StoicheiaHymnRoute
  StoicheiaIsopsephyRoute: typeof StoicheiaIsopsephyRoute
  StoicheiaXeniaRoute: typeof StoicheiaXeniaRoute
  StoicheiaIndexRoute: typeof StoicheiaIndexRoute
}

const StoicheiaRouteChildren: StoicheiaRouteChildren = {
  StoicheiaCalendarRoute: StoicheiaCalendarRoute,
  StoicheiaDoctrineRoute: StoicheiaDoctrineRoute,
  StoicheiaHoraeRoute: StoicheiaHoraeRoute,
  StoicheiaHymnRoute: StoicheiaHymnRoute,
  StoicheiaIsopsephyRoute: StoicheiaIsopsephyRoute,
  StoicheiaXeniaRoute: StoicheiaXeniaRoute,
  StoicheiaIndexRoute: StoicheiaIndexRoute,
}

const StoicheiaRouteWithChildren = StoicheiaRoute._addFileChildren(
  StoicheiaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlmanacRoute: AlmanacRoute,
  ArchetypesRoute: ArchetypesRoute,
  AtlasRoute: AtlasRoute,
  BondRoute: BondRoute,
  CircleRoute: CircleRoute,
  ClaimRoute: ClaimRoute,
  CountRoute: CountRoute,
  DoctrineRoute: DoctrineRoute,
  HouseRoute: HouseRoute,
  KeyRoute: KeyRoute,
  LoginRoute: LoginRoute,
  StoicheiaRoute: StoicheiaRouteWithChildren,
  ApiCardRoute: ApiCardRoute,
  OgFileRoute: OgFileRoute,
  PSlugRoute: PSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
